title: Aashir Hussain
description: Software Developer • AI/ML & Data • Embedded Systems
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM