title: Aashir Hussain
description: Software Developer • AI/ML & Data • Embedded Systems
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
# Optional: add a link to our extra CSS
include:
  - assets/css/custom.css